### ISSUE TITLE
Narrow width layout for small components

### ISSUE THREAD

**Issue by soygul** [majorna/majorna#108]
we can just try to remove flex grow

**Comment by soygul** [comment]
done with:

```css
@media screen and (min-width: 800px) {
    .w-m {
        width: 750px;
    }

    .w-s {
        width: 500px;
    }
}
```
