### ISSUE TITLE
Limit page width depending on total screen width

### ISSUE THREAD

**Issue by soygul** [majorna/majorna#42]
First step into grid layout -or- precursor to it, in case we decide to not complicate the layout with grid for now.

**Comment by soygul** [comment]
done:

```css
/* layout */
#root {
    /* center and limit content width */
    max-width: 1216px; /* limit: widescreen */
    margin-right: auto;
    margin-left: auto; /* equal left-right margin after max-width is exceeded */

    display: flex;
    flex-direction: column;
    flex-grow: 1; /* so pages with insufficient width will not collapse into a narrow column */
}
```
